### ISSUE TITLE
Error Removing Claims

### ISSUE THREAD

**Issue by AlonCG** [brockallen/BrockAllen.MembershipReboot#352]
Thanks again for your hard work on this project (and for all those that contribute as well).

This is the same error as the OP in #340 

Unfortunately, that issue was closed, however the issue did not seem to be resolved for the OP ... @julianpaulozzi sortof hijacked the issue and it was closed. (Please no offense meant). 

So, back to the issue if you don't want to read #340 ... when deleting a claim (with latest EF and MR from NuGet), I receive the following error:

```
System.InvalidOperationException was caught
  _HResult=-2146233079
  _message=The operation failed: The relationship could not be changed because one or more of the foreign-key properties is non-nullable. When a change is made to a relationship, the related foreign-key property is set to a null value. If the foreign-key does not support null values, a new relationship must be defined, the foreign-key property must be assigned another non-null value, or the unrelated object must be deleted.
  HResult=-2146233079
  IsTransient=false
  Message=The operation failed: The relationship could not be changed because one or more of the foreign-key properties is non-nullable. When a change is made to a relationship, the related foreign-key property is set to a null value. If the foreign-key does not support null values, a new relationship must be defined, the foreign-key property must be assigned another non-null value, or the unrelated object must be deleted.
  Source=EntityFramework
  StackTrace:
       at System.Data.Entity.Core.Objects.ObjectContext.PrepareToSaveChanges(SaveOptions options)
       at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
       at System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
       at System.Data.Entity.Internal.InternalContext.SaveChanges()
       at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
       at System.Data.Entity.DbContext.SaveChanges()
       at E_Tabs.Dashboards.Infrastructure.Data.EtdsContext.SaveChanges(Int32 userAccountKey) in c:\01 Development\Dashboard System\Source Code\02 Infrastructure\E-Tabs.Dashboards.Infrastructure\Data\EtdsContext.cs:line 442
       at E_Tabs.Dashboards.Infrastructure.Data.EtdsContext.SaveChanges() in c:\01 Development\Dashboard System\Source Code\02 Infrastructure\E-Tabs.Dashboards.Infrastructure\Data\EtdsContext.cs:line 417
       at BrockAllen.MembershipReboot.Ef.DbContextUserAccountRepository`2.SaveChanges() in c:\ballen\github\BrockAllen.MembershipReboot\src\BrockAllen.MembershipReboot.Ef\DbContextUserAccountRepository.cs:line 62
       at BrockAllen.MembershipReboot.Ef.DbContextUserAccountRepository`2.Update(TAccount item) in c:\ballen\github\BrockAllen.MembershipReboot\src\BrockAllen.MembershipReboot.Ef\DbContextUserAccountRepository.cs:line 95
       at BrockAllen.MembershipReboot.EventBusUserAccountRepository`1.Update(TAccount item) in c:\ballen\github\BrockAllen.MembershipReboot\src\BrockAllen.MembershipReboot\Repository\EventBusUserAccountRepository.cs:line 71
       at BrockAllen.MembershipReboot.UserAccountService`1.UpdateInternal(TAccount account) in c:\ballen\github\BrockAllen.MembershipReboot\src\BrockAllen.MembershipReboot\AccountService\UserAccountService.cs:line 174
       at BrockAllen.MembershipReboot.UserAccountService`1.Update(TAccount account) in c:\ballen\github\BrockAllen.MembershipReboot\src\BrockAllen.MembershipReboot\AccountService\UserAccountService.cs:line 161
       at BrockAllen.MembershipReboot.UserAccountService`1.RemoveClaim(Guid accountID, String type) in c:\ballen\github\BrockAllen.MembershipReboot\src\BrockAllen.MembershipReboot\AccountService\UserAccountService.cs:line 2395
       at E_Tabs.Dashboards.Web.Code.Helpers.MembershipHelper.ChangeAlternateEmail(UserAccountService accountService, Guid id, String address) in c:\01 Development\Dashboard System\Source Code\03 Web Applications\E-Tabs.Dashboards.Web\Code\Helpers\MembershipHelper.cs:line 131
  InnerException: 
```

Now, I have in fact called 

```
this.RegisterUserAccountChildTablesForDelete<EtdsUserAccount>();
```

in my DBContext constructor. This does not do anything for the issue. Any other suggestions? And ... I do not believe this is related to Thinktecture.IdentityManager.

**Comment by alex9o6** [comment]
@AlonCG I know it has been a lot of time since you asked your question. But in case you are still interested - ensure that you define all the properties of your custom UserAccount-derived type with the virtual keyword. This was the case for me.
