### ISSUE TITLE
2 tests are currently failing (as of 16/7/2015)

### ISSUE THREAD

**Issue by Allann** [brockallen/BrockAllen.MembershipReboot#548]
test 1-
Test Name:	CreateAccount_CanPassCreatedDate_UsesCreatedDate
Test FullName:	BrockAllen.MembershipReboot.Test.AccountService.UserAccountServiceTests.CreateAccount_CanPassCreatedDate_UsesCreatedDate
Test Source:	C:\Dev\Third Party\Identity And Access Control\BrockAllen.MembershipReboot-master\src\BrockAllen.MembershipReboot.Test\AccountService\UserAccountServiceTests.cs : line 677
Test Outcome:	Failed
Test Duration:	0:00:00.0348994

Result StackTrace:	
at BrockAllen.MembershipReboot.UserAccountService`1.Init(TAccount account, String tenant, String username, String password, String email, Nullable`1 id, Nullable`1 dateCreated) in C:\Dev\Third Party\Identity And Access Control\BrockAllen.MembershipReboot-master\src\BrockAllen.MembershipReboot\AccountService\UserAccountService.cs:line 507
   at BrockAllen.MembershipReboot.UserAccountService`1.CreateAccount(String tenant, String username, String password, String email, Nullable`1 id, Nullable`1 dateCreated, TAccount account) in C:\Dev\Third Party\Identity And Access Control\BrockAllen.MembershipReboot-master\src\BrockAllen.MembershipReboot\AccountService\UserAccountService.cs:line 456
   at BrockAllen.MembershipReboot.UserAccountService`1.CreateAccount(String username, String password, String email, Nullable`1 id, Nullable`1 dateCreated) in C:\Dev\Third Party\Identity And Access Control\BrockAllen.MembershipReboot-master\src\BrockAllen.MembershipReboot\AccountService\UserAccountService.cs:line 431
   at BrockAllen.MembershipReboot.Test.AccountService.UserAccountServiceTests.CreateAccount_CanPassCreatedDate_UsesCreatedDate() in C:\Dev\Third Party\Identity And Access Control\BrockAllen.MembershipReboot-master\src\BrockAllen.MembershipReboot.Test\AccountService\UserAccountServiceTests.cs:line 679
Result Message:	
Test method BrockAllen.MembershipReboot.Test.AccountService.UserAccountServiceTests.CreateAccount_CanPassCreatedDate_UsesCreatedDate threw exception: 
System.Exception: dateCreated can't be in the future

Test 2-
Test Name:	GetValue_NullClaims_ReturnsNull
Test FullName:	BrockAllen.MembershipReboot.Test.GroupService.ClaimsExtensionsTests.GetValue_NullClaims_ReturnsNull
Test Source:	C:\Dev\Third Party\Identity And Access Control\BrockAllen.MembershipReboot-master\src\BrockAllen.MembershipReboot.Test\Localisation\LocalisationTests.cs : line 18
Test Outcome:	Failed
Test Duration:	0:00:00.0750119

Result StackTrace:	at BrockAllen.MembershipReboot.Test.GroupService.ClaimsExtensionsTests.GetValue_NullClaims_ReturnsNull() in C:\Dev\Third Party\Identity And Access Control\BrockAllen.MembershipReboot-master\src\BrockAllen.MembershipReboot.Test\Localisation\LocalisationTests.cs:line 50
Result Message:	Assert.AreEqual failed. Expected:<Kontot är avslutat.>. Actual:<Account stängd.>.

**Comment by girtsl** [comment]
The reason and fix for test 1 is in #534.

**Comment by brockallen** [comment]
I just merged that PR and the tests (for me) are all passing (after I fixed one).

**Comment by brockallen** [comment]
@girtsl can you re-check and confirm that they're working for you now? thx

**Comment by girtsl** [comment]
Hi! The only tests failing for me involved the use of DateTime.Now instead of DateTime.UtcNow, which are now fixed.
@Allann was the OP.

**Comment by brockallen** [comment]
Ok, thanks.

Can we close this now @Allann?
